project:
  type: website
  output-dir: docs

website:
  title: "Dinámica - FIS1514"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cinematica.qmd
      - unidad-2.qmd
      - unidad-3.qmd
      - unidad-4.qmd
      - ejercicios.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

