---
title: "Unidad 1"
author: "Nicolás Ulloa Gatica"
format:
  html:
    code-fold: true
jupyter: python3
mathjax: true
---

# Fundamentos de Cinemática

## Desplazamiento

El desplazamiento de una partícula (u objeto) se define como el cambio de posición. Si la posición inicial de la partícula está descrita por el vector $\vec{r}_1$ y la posición final corresponde a $\vec{r}_2$, entonces el desplazamiento estará dado por:

$$
\Delta \vec{r} := \vec{r}_2 - \vec{r}_1
$$

## Velocidad

La velocidad se define como el desplazamiento por unidad de tiempo. En otras palabras, es la razón de cambio entre la posición y el tiempo. Si una partícula se encuentra en la posición $\vec{r}_1$ en el instante $t_1$ y se desplaza a la posición $\vec{r}_2$ en el instante de tiempo $t_2$, su **velocidad media** será:

$$
\vec{v}_m := \frac{\vec{r}_2 - \vec{r}_1}{t_2 - t_1} = \frac{\Delta \vec{r}}{\Delta t}
$$

Lo anterior se define como velocidad media, dado que entre el instante $t_1$ y el instante $t_2$ pudieron existir diversos cambios de velocidad que no se contemplan en la ecuación anterior.

Para tener información de la velocidad durante todo el tiempo, al saber cómo varía la posición $\vec{r}$ respecto al tiempo $t$, esto se logra mediante el cálculo diferencial. Es decir, la **velocidad instantánea**, o simplemente velocidad, se define como:

$$
\vec{v} := \lim_{\Delta t \rightarrow 0} \frac{\Delta \vec{r}}{\Delta t} = \frac{d\vec{r}}{dt}
$$
A continuación se muestra una simulación del movimiento rectilineo de una partícula, junto a su grafico de posición vs velocidad.

## Aceleración

De forma análoga a lo anterior, la aceleración se define como el cambio de velocidad en un intervalo de tiempo. Así, la **aceleración media** será:

$$
\vec{a}_m := \frac{\vec{v}_2 - \vec{v}_1}{t_2 - t_1} = \frac{\Delta \vec{v}}{\Delta t}
$$

Mientras que la **aceleración instantánea**, o simplemente aceleración, se define como:

$$
\vec{a} := \lim_{\Delta t \rightarrow 0} \frac{\Delta \vec{v}}{\Delta t} = \frac{d\vec{v}}{dt}
$$

## Ecuaciones de movimiento

Dadas las ecuaciones anteriores, es posible encontrar ecuaciones que caractericen el movimiento de una partícula mediante la integración. Por ejemplo, para una **aceleración constante** se tiene:

$$
\int \vec{a} \, d\tau = \int \frac{d\vec{v}}{d\tau} \, d\tau
$$

Lo que lleva a:

$$
\boxed{\vec{v}(t) = \vec{v}_0 + \vec{a} \cdot t}
$$

De igual forma, si se integra nuevamente la ecuación anterior, se obtiene:

$$
\boxed{\vec{r}(t) = \vec{r}_0 + \vec{v_0} \cdot t + \frac{1}{2} \vec{a} \cdot t^2}
$$

Esta ecuación es conocida como la **ecuación itinerario**, y solo aplica para los casos en los que la aceleración es constante. Sin embargo, se puede obtener, a partir del procedimiento anterior, una ecuación de movimiento para cualquier partícula a partir de su velocidad o aceleración.



# Cinemática en 2 dimensiones

## Consideraciones

Con una buena comprensión del movimiento unidimensional, el movimiento bi o tridimensional no presenta mayores complicaciones al tener en mente tres consideraciones:

- El sistema de coordenadas es siempre ortogonal, ya sea en coordenadas cartesianas o polares. Esto implica que todo lo que sucede en una dimensión, no afecta a la otra dimensión.
- El tiempo, para un mismo instante, es el mismo en ambas dimensiones.
- Para cada dimensión se aplica su ecuación respectiva y si existen cantidades vectoriales, se deben descomponer en cada una de las dimensiones para realizar el análisis matemático. En el título *Conceptos previos* se encuentra información respecto a la descomposición de vectores.

## Metodología para resolución de problemas

Generalmente, los problemas iniciales de cinemática en 2 dimensiones conservan la misma lógica para ser resueltos. Esta lógica se puede resumir en 6 pasos:

1. **Definir el origen y sistema de coordenadas** más útil. Si el problema trata de un movimiento circular, lo más probable es que sea más simple utilizar coordenadas polares.
2. **Identificar** las cantidades conocidas y las que se piden.
3. **Descomponer** las cantidades vectoriales en cada eje del sistema coordenado, que serán utilizadas al escribir las ecuaciones de movimiento.
4. **Establecer las ecuaciones de movimiento** para cada eje del sistema de coordenadas. En coordenadas cartesianas, y con aceleración constante, por ejemplo, las ecuaciones serían:

$$
\vec{r}_x(t) = r_{0x} + v_{0x}\cdot t + \frac{1}{2}\cdot a_x \cdot t^2 \hspace{2cm} \vec{v}_x(t) = v_{0x} + a_x\cdot t
$$

$$
\vec{r}_y(t) = r_{0y} + v_{0y}\cdot t + \frac{1}{2}\cdot a_y \cdot t^2 \hspace{2cm} \vec{v}_y(t) = v_{0y} + a_y\cdot t
$$

5. **Evaluar con las cantidades conocidas** para algún instante, posición, velocidad o aceleración.

Por ejemplo, una partícula comienza a moverse desde el origen $(s_0=0)$, $(v_0=0)$. La partícula alcanza velocidad $b$ en el eje $x$ en el instante $t = t_1$ y llega a la posición $H$ en el eje $y$ para ese mismo instante. Si la aceleración en el eje $y$ es $c$, las ecuaciones serán:

$$
\vec{r}_x(t_1) = \frac{1}{2}\cdot a_x \cdot t_1^2 \hspace{2cm} \vec{v}_x(t_1) = b = a_x\cdot t_1
$$

$$
\vec{r}_y(t_1) = H = \frac{1}{2}\cdot c \cdot t_1^2 \hspace{2cm} \vec{v}_y(t_1) = c\cdot t_1
$$

Con estas relaciones ya es posible describir el movimiento completo de la partícula.

6. Por último, solo queda **resolver el sistema de ecuaciones** y encontrar lo que piden en el problema. Para el ejemplo anterior, el sistema de ecuaciones en el instante $t_1$, de manera más ordenada, sería:

$$
\begin{aligned}
&r_x = \frac{1}{2} \cdot a_x \cdot t_1^2\\
&b=a_x\cdot t_1\\
&H=\frac{1}{2} \cdot c \cdot t_1^2\\
&v_y = c\cdot t_1
\end{aligned}
$$

Las incógnitas (cantidades desconocidas, no entregadas en el enunciado) son $r_x$, $t_1$, $v_y$, $a_x$. Al ser 4 incógnitas y 4 ecuaciones, es posible resolver el sistema y encontrar el valor de cualquiera de las 4 incógnitas en función de cantidades conocidas.

# Coordenadas Polares

Las coordenadas polares son un sistema de coordenadas bidimensional que permite localizar cualquier punto en el plano a través de un ángulo y una distancia. De esta forma, se define un **vector posición** $\vec{r}=(r,\theta)$ en que $r$ es la distancia desde el origen (o polo) al punto de interés y $\theta$ es el ángulo que se forma entre el eje horizontal (o eje polar) y el punto de interés.

## Conversión entre coordenadas cartesianas y polares

Por trigonometría se tienen las siguientes conversiones entre coordenadas cartesianas y polares[^1]:

$$
    x=r \cdot \cos(\theta) \quad y=r \cdot \sin(\theta) \quad r=\sqrt{x^2 + y^2} \quad \theta=\arctan{\frac{y}{x}}
$$

[^1]: No siempre es cierto que $\theta = \arctan{\frac{y}{x}}$, depende del intervalo.

## Vectores unitarios en coordenadas polares

En las coordenadas cartesianas, se tienen dos vectores unitarios para describir el plano: $\{\mathbf{\hat{i}}, \mathbf{\hat{j}}\}$, los cuales están fijos en el origen y son ortogonales. En el caso de las coordenadas polares también se tendrán dos vectores unitarios ortogonales, pero móviles, situándose siempre sobre el punto de interés.

Al describir el movimiento de una partícula en coordenadas polares, se utilizan los vectores $\mathbf{\hat{r}}$ y $\mathbf{\hat{\theta}}$, definidos como:

- **Vector $\mathbf{\hat{r}}$**: Tiene como dirección la línea que traza $r$ (la distancia) y sentido positivo cuando apunta fuera del origen.
- **Vector $\mathbf{\hat{\theta}}$**: Tiene dirección perpendicular a $\mathbf{r}$ y sentido positivo cuando apunta de forma tal que $\mathbf{\theta}$ tiende a aumentar.

De estas definiciones se obtienen las siguientes relaciones:

$$
    \hat{r}=\cos\theta \hat{i} + \sin{\theta}\hat{j} \quad \hat{\theta} = -\sin{\theta}\hat{i} + \cos{\theta}\hat{j}
$$

Además:

$$
    \frac{d{\hat{r}}}{d{\theta}} =  \hat{\theta} \quad \frac{d\hat{\theta}}{d\theta} = -\hat{r}
$$

## Movimiento en coordenadas polares

Ahora es posible describir completamente el movimiento de una partícula en el plano. Se comienza escribiendo la ecuación de posición y luego derivando respecto al tiempo para obtener la velocidad y la aceleración:

$$
    \vec{r} = r\hat{r}
$$

$$
    \vec{v} = \dot{r}\hat{r} + r \dot{\theta}\hat{\theta}
$$

$$
    \vec{a} = (\ddot{r} - r \dot{\theta}^2)\hat{r} + (2\dot{r} \dot{\theta} + r \ddot{\theta})\hat{\theta}
$$

# Movimiento Relativo


En física, para describir magnitudes y propiedades de un sistema, se debe hacer siempre respecto a un **sistema de referencia**, es decir, se utiliza un conjunto de convenciones para simplificar el entendimiento de una misma situación observada desde distintos lugares espaciales. Por esto, el movimiento de una partícula o cuerpo es siempre relativo a algún punto y, si el interés es conocer el movimiento respecto a otro cuerpo que también se está moviendo, se deben tener algunas consideraciones.

Si se quiere describir la posición de un objeto $A$ respecto a un objeto $B$, el vector de posición puede ser denotado por $\vec{r}_{A/B}$ y se leerá como *la posición de $A$ respecto de $B$*, es decir, un observador en $B$ medirá una distancia $r$ entre él y $A$[^2].

[^2]: Es análogo para la velocidad y aceleración.

Analizando geométricamente los vectores de posición, se puede demostrar rápidamente que:

$$
    \vec{r}_{A/B}=\vec{r}_A - \vec{r}_B
$$

Donde $\vec{r}_A$ y $\vec{r}_B$ son los vectores de posición medidos desde un observador externo (típicamente, el origen del sistema de coordenadas utilizado).

La relación anterior se puede derivar respecto al tiempo y obtener las ecuaciones de movimiento relativo para la velocidad y la aceleración:

$$
    \vec{v}_{A/B}=\vec{v}_A - \vec{v}_B
$$

$$
    \vec{a}_{A/B}=\vec{a}_A - \vec{a}_B
$$



